### ISSUE TITLE
Question: how does this differ from dotnet list

### ISSUE THREAD

**Issue by explunit** [digitalcoyote/NuGetDefense#143]
Cool-looking project. Question though...

Do you expect the results from this tool to differ from those obtained from `dotnet list mysolution.sln package --vulnerable --include-transitive`

I see in the documentation that you mention `dotnet list` and that its output can be confusing, but my question is whether you expect the result from this tool to be different in some way (if so, how), or to run more quickly, etc?

**Comment by digitalcoyote** [comment]
There are a few ways this works differently than dotnet list. If you use the Nuget package to run the scan, it gives you feedback in the IDE on each build. Additionally, it allows whitelisting/blacklisting packages, filtering reported vulnerabilities based on cvs score or attack vectors,  outputting a machine readable report of each scan, and ignoring vulnerabilities you've already acknowledged as not affecting your code or acceptable in the short term.

I use it to scan on each build and as part of security reviews over new dependencies. If they haven't been approved and added to the whitelist, they don't pass the scan.

It has been a bit since I evaluated the --vulnerable option though on dotnet list but previously I believe it didn't return a non-zero exit code when vulnerabilities were found (so CI usage required parsing it out), and it didn't provide some of the vulnerability details that is output by NuGetDefense (from whichever vulnerability source reported it).

**Comment by explunit** [comment]
Thanks, that makes sense.
