### ISSUE TITLE
nugetdefense.targets is not cross-platform.

### ISSUE THREAD

**Issue by gudaolLMI** [digitalcoyote/NuGetDefense#2]
Hi,
great work!

I ran into some issue on Windows, as having the NuGet in dependecies results in the following in VS output:
1>'...nuget\packages\nugetdefense\0.0.2\build\../tools/netcoreapp3.1/NuGetDefense' is not recognized as an internal or external command,

My q&d fix for Windows is to replace the line in nugetdefense.targets to the following:
`<NuGetDefenseExe>dotnet.exe $(MSBuildThisFileDirectory)..\tools\netcoreapp3.1\NuGetDefense.dll</NuGetDefenseExe>`

This way, it runs correctly - but still not cross platform.
Found related issue with no clear solution: https://github.com/microsoft/msbuild/issues/1024

**Comment by digitalcoyote** [comment]
The recommendation I saw is to have it conditionally use a different build of the tool based on the platform the project is targeting. I'll be working on this to see what I can do.

**Comment by digitalcoyote** [comment]
Got it to work with .Net Core 3.1 on both Linux and Windows, but targeting the .Net Framework is giving it fits: 

`  Microsoft.Common.CurrentVersion.targets(3056, 5): [MSB4216] Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\3.1.101\MSBuild.exe" exists and can be run.`

I'll have to look into this later though since I'm out of time this morning.

**Comment by digitalcoyote** [comment]
59f6789c32f8778e07a5eef825f63cc80af22cf8 should fix the issue. I've tested on latest Win10 (net48 and netcoreapp3.1 projects) as well as Linux (netcoreapp3.1 project).

**Comment by gudaolLMI** [comment]
Thank you for the quick fix! Can confirm, it is working now OOB. Closing accordingly.
