### ISSUE TITLE
Solution level NuGetDefense.json

### ISSUE THREAD

**Issue by jeffadavidson** [digitalcoyote/NuGetDefense#44]
**What is the Feature? Please describe.**
When NugetDefense is installed on the project a NuGetDefense.json is created. If you have a solution that contains multiple projects a NuGetDefense.json is required for each project. It would be nice if NugetDefense behaved a bit like .nugetconfig where when the file is not found in the project folder it checks parent folders. This would allow a single NuGetDefense.json to set the defense configuration for an entire solution

**Use Case**
When a project is part of a larger solution and all have NuGetDefense installed

**Comment by digitalcoyote** [comment]
I've been considering the issue with large solutions and this is one of the problems (configuration). Due to problems with rate limiting, I believe the better solution is to add solution level scanning to the dotnet tool variant with a single solution level configuration. 

That said, I'm willing to look into this as well. The biggest problem is that msbuild doesn't give much information about the solution or other projects. 

Do you have any suggestions on how this might work? I have some ideas, but I personally plan on using the global tool for larger solutions.

**Comment by digitalcoyote** [comment]
I'm going to try to throw a prerelease together tonight, but I'll be partially unavailable for the the next 24 hours afterwards. It may be Sunday before I have a chance to test it and do a full release.

**Comment by digitalcoyote** [comment]
Got 1.0.15-pre0002 (.Net Core 3.1) and 2.0.2-pre0002 (.Net 5) published to NuGet.org. I'll try to do the testing tomorrow before pushing out the full release, but you may want to try it out to make sure it's what you were expecting (only looking one level higher).  I'm considering letting it look 2 levels higher instead as I think I've seen some solution structures that would follow that pattern as well.

**Comment by jeffadavidson** [comment]
@digitalcoyote I can make 1 level higher work with my solution design. Thanks a lot for the quick response as always

**Comment by digitalcoyote** [comment]
Should be Added in v1.0.15 as well as v2.0.2
