### ISSUE TITLE
Include dependencies from all referenced projects

### ISSUE THREAD

**Issue by bjowes** [digitalcoyote/NuGetDefense#47]
**What is the Feature? Please describe.**
Include dependencies from all referenced projects in the scan.

**Use Case**
I just started evaluating NuGetDefense for use in the solutions within my organisation. Most of our solutions consist of multiple projects following a layered architecture (business logic, contract model, data layer ...).  I would prefer that adding NuGetDefense to the top level project would scan all the referenced projects too (also nested references).

**Describe alternatives you've considered**
It seems quite redundant to be forced to add NuGetDefense to all of the projects.

**Additional context**
Tested with 2.0.2 and 1.0.15.1
We are using Net Core 3.1, Visual Studio 2019 16.8.2

**Comment by digitalcoyote** [comment]
I'm actually already working on a solution level scanning for the dotnet tool variant that will share s lot of code with this. Work and the holidays have me working at half pace at the moment. I'll try to get this out a little quicker.

Any opinions on whether or not to tie this into the transitive dependency checking? (Transitive checking actually scans project references, but doesn't report the errors for those projects)

**Comment by digitalcoyote** [comment]
Work is going well on this (combined with the sln scanning for the dotnet tool).

I'm using dotnet list to get them for ask projects and loading up the project files for legacy projects. Reporting the vulnerabilities correctly is a bit more challenging (what I'm working on now). The resolved versions may need to be fixed in either the referenced project or in the current project instead. I'll be thinking about the most intuitive and performance ways to report what came from where.

**Comment by bjowes** [comment]
Thanks for working on this @digitalcoyote!
As for your question, I think there are different use cases where both variants make sense. 

A solution may consist of multiple "trees" of projects that are not completely connected. So scanning all projects in a solution will give the most complete picture. 

However, the solution often contains unit test projects or benchmarking projects, where the developer probably don't want the build to fail if a dependency has a vulnerability. Picking a specific root project and scanning each referenced project makes more sense in that case. 

An alternative could be to use sensible defaults - for instance test projects can be detected from project type. It would probably be a good idea to simply warn for vulnerabilities in those projects, while keeping this configurable. If this is applied, together with some straight forward way to exclude specific projects, I think the solution level scanning is the preferred method.

But where is the solution level scanning installed and configured? Or is that a CLI tool rather than a project Nuget?

**Comment by digitalcoyote** [comment]
[NuGetDefense.Tool](https://www.nuget.org/packages/NuGetDefense.Tool) is getting the solution level scanning for CI use.

The main reason I'd add that separately is that in a project such as NuGetDefense where the referenced projects are also distributed as NuGet packages, a vulnerability in one may not exist in the top level project.

For example, if ClassLib1.csproj has log4Net v2.0.8 installed, NuGetDefense will detect the vulnerability in it. But if ConsoleApp1.csproj has specifically installed log4Net 2.0.12 it will not warn or error for the vulnerability because it will instead include the newer version of the log4net package. Then when distributing ClassLib1, I am distributing a vulnerable library.

Solution level scanning could scan each individual project and warn/error based on the resolved versions for that project (including resolved versions based on referenced projects).

I intend to release both Solution level scanning and including referenced project versions in the next release.

**Comment by digitalcoyote** [comment]
This feature has slowed down some due to the holidays and an increased workload from my day job. 

I'm going to be referencing the solution file using dotnet list to get referenced project packages. I'd like to get that released before reworking to indicate which project had which package/vulnerability (and potentially enabling solution level scanning since I'll be loading the solution file).

**Comment by digitalcoyote** [comment]
Got a pre-release that has the basic functionality. https://www.nuget.org/packages/NuGetDefense/2.1.0-pre0007

It should report any vulnerabilities in referenced projects. I hope to flesh this out later. as it stands, I'll need to clean up the code some before I do anything else.

**Comment by digitalcoyote** [comment]
Another pre-release coming. Known issues in this one:
-  It does scan the project references, but it reports them incorrectly as originating in the top level project
- Vulnerabilities for referenced projects that have the same id (but different version) as a package in the top level project are reported regardless of vulnerable status

**Comment by digitalcoyote** [comment]
Should be implemented in v1.0.16 and v2.1.0. I'm considering this a feature as a prerelease for now. I think there are cases where this could fail and it needs some optimizations.
